Clarification on the snarkOS --ip option
Connecting using an ip address seems to require the port to also be specified. 
Failing to specify the port results the in the following error message:

> Error: Crate("std::net::AddrParseError", "AddrParseError(())")